const MarkBillboards = [
  {
    image: '/static/images/marker/mark_bg.png',
    font: 'bold 28px "楷体"',
    fillStyle: '#fff9f2',
    x: 82,
    y: 52,
    pixelOffsetX: 16,
    pixelOffsetY: -26,
  },
  {
    image: '/static/images/marker/mark_bg2.png',
    font: 'bold 28px "楷体"',
    fillStyle: '#fff9f2',
    x: 82,
    y: 52,
    pixelOffsetX: 16,
    pixelOffsetY: -26,
  },
  {
    image: '/static/images/marker/mark_bg3.png',
    font: 'bold 28px "楷体"',
    fillStyle: '#fff9f2',
    x: 82,
    y: 52,
    pixelOffsetX: 16,
    pixelOffsetY: -26,
  },
  {
    image: '/static/images/marker/mark_bg4.png',
    font: 'bold 32px "楷体"',
    fillStyle: '#fff9f2',
    x: 88,
    y: 62,
    pixelOffsetX: 10,
    pixelOffsetY: -26,
  },
  {
    image: '/static/images/marker/mark_bg5.png',
    font: 'bold 32px "楷体"',
    fillStyle: '#fff9f2',
    x: 88,
    y: 62,
    pixelOffsetX: 10,
    pixelOffsetY: -26,
  },
  {
    image: '/static/images/marker/mark_bg7.png',
    font: 'bold 28px "楷体"',
    fillStyle: '#fff9f2',
    x: 70,
    y: 39,
    pixelOffsetX: 12,
    pixelOffsetY: 10,
  },
  {
    image: '/static/images/marker/mark_bg8.png',
    font: 'bold 28px "楷体"',
    fillStyle: '#ffefc5',
    x: 128,
    y: 52,
    pixelOffsetX: 0,
    pixelOffsetY: -16,
  },
  {
    image: '/static/images/marker/mark_bg9.png',
    font: 'bold 28px "楷体"',
    fillStyle: '#fff9f2',
    x: 78,
    y: 42,
    pixelOffsetX: 18,
    pixelOffsetY: 10,
  },
  {
    image: '/static/images/marker/mark_bg10.png',
    font: 'bold 28px "楷体"',
    fillStyle: '#fff9f2',
    x: 78,
    y: 42,
    pixelOffsetX: 16,
    pixelOffsetY: -10 ,
  },
  {
    image: '/static/images/marker/mark_bg11.png',
    font: 'bold 28px "楷体"',
    fillStyle: '#fff9f2',
    x: 78,
    y: 42,
    pixelOffsetX: 16,
    pixelOffsetY: -10 ,
  },
];

export default MarkBillboards;
